"""
DriveSafe AI - PDF Report Generator
=======================================
Generates a clean, professional PDF driving-safety report
for a completed session using ReportLab.
"""

import os
import logging
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, Image, KeepTogether,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.graphics import renderPDF

from config import REPORTS_DIR

logger = logging.getLogger(__name__)

# --- Colour Palette ---
PRIMARY    = colors.HexColor("#3B5BFF")
ACCENT     = colors.HexColor("#00C9A7")
DANGER     = colors.HexColor("#FF4058")
WARNING    = colors.HexColor("#FFB703")
SUCCESS    = colors.HexColor("#06D6A0")
NAVY       = colors.HexColor("#0D1B3E")
CARD_BG    = colors.HexColor("#F5F7FF")
WHITE      = colors.white
LIGHT_LINE = colors.HexColor("#E2E8F0")
MID_GREY   = colors.HexColor("#94A3B8")
TEXT_DARK  = colors.HexColor("#0D1B3E")
TEXT_MED   = colors.HexColor("#334155")
TEXT_LIGHT = colors.HexColor("#64748B")

PAGE_W, PAGE_H = A4


# --- Helper Functions ---

def _score_color(score):
    if score >= 80:
        return SUCCESS
    elif score >= 60:
        return WARNING
    return DANGER


def _grade_label(score):
    if score >= 90:
        return "Excellent"
    elif score >= 80:
        return "Good"
    elif score >= 60:
        return "Fair"
    return "Needs Improvement"


def _severity_color(severity):
    s = severity.upper()
    if s == "DANGER":
        return DANGER
    if s == "WARNING":
        return WARNING
    return ACCENT


def _pct_bar(pct, color, width=140, height=9):
    """Return a horizontal progress-bar Drawing."""
    d = Drawing(width, height)
    d.add(Rect(0, 0, width, height,
               fillColor=LIGHT_LINE, strokeColor=None, rx=4, ry=4))
    fw = max(0, min(width, width * pct / 100))
    if fw > 0:
        d.add(Rect(0, 0, fw, height,
                   fillColor=color, strokeColor=None, rx=4, ry=4))
    return d


# --- Report Generator ---

class ReportGenerator:
    """Generates a clean PDF safety report for a completed driving session."""

    def __init__(self):
        self._styles = getSampleStyleSheet()
        self._add_custom_styles()

    def _add_custom_styles(self):
        def _add(name, **kw):
            if name not in self._styles:
                self._styles.add(ParagraphStyle(name=name, **kw))

        _add("SectionHdr",
             fontSize=12, textColor=PRIMARY,
             spaceBefore=0, spaceAfter=6,
             fontName="Helvetica-Bold", leading=16)
        _add("SmallGrey",
             fontSize=8, textColor=TEXT_LIGHT,
             fontName="Helvetica", leading=11)
        _add("CardLabel",
             fontSize=8, textColor=TEXT_LIGHT,
             fontName="Helvetica", leading=10)
        _add("CardValue",
             fontSize=11, textColor=TEXT_DARK,
             fontName="Helvetica-Bold", leading=14)
        _add("FooterStyle",
             fontSize=7.5, textColor=MID_GREY,
             alignment=TA_CENTER, fontName="Helvetica")

    # --- Page Header / Footer ---

    def _on_page(self, canvas, doc):
        """Draws the branded header and footer on every page."""
        canvas.saveState()

        # Header navy bar
        canvas.setFillColor(NAVY)
        canvas.rect(0, PAGE_H - 1.6 * cm, PAGE_W, 1.6 * cm, fill=1, stroke=0)
        canvas.setFillColor(PRIMARY)
        canvas.rect(0, PAGE_H - 1.6 * cm, 0.4 * cm, 1.6 * cm, fill=1, stroke=0)

        canvas.setFont("Helvetica-Bold", 9)
        canvas.setFillColor(WHITE)
        canvas.drawString(1.0 * cm, PAGE_H - 1.05 * cm,
                          "DriveSafe AI  \u2022  Driver Safety Report")
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#A5B4FC"))
        canvas.drawRightString(PAGE_W - 1.5 * cm, PAGE_H - 1.05 * cm,
                               "Page %d" % doc.page)

        # Footer rule
        canvas.setFillColor(LIGHT_LINE)
        canvas.rect(1.5 * cm, 1.0 * cm, PAGE_W - 3.0 * cm, 0.3, fill=1, stroke=0)
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(MID_GREY)
        canvas.drawCentredString(
            PAGE_W / 2, 0.7 * cm,
            "Generated by DriveSafe AI  \u2022  %s  \u2022  Confidential"
            % datetime.now().strftime("%d %b %Y, %H:%M")
        )
        canvas.restoreState()

    # --- Score Summary Cards ---

    def _score_card_table(self, safety, attention):
        sc_col = _score_color(safety)
        at_col = PRIMARY

        def _cell(label, score, col):
            return [
                Paragraph(
                    "<b>%d</b>" % int(round(score)),
                    ParagraphStyle("sn", fontSize=28, fontName="Helvetica-Bold",
                                   textColor=col, alignment=TA_CENTER, leading=34)
                ),
                Paragraph(
                    "/100",
                    ParagraphStyle("sd", fontSize=9, fontName="Helvetica",
                                   textColor=TEXT_LIGHT, alignment=TA_CENTER, leading=12)
                ),
                Paragraph(
                    "<b>%s</b>" % label,
                    ParagraphStyle("sl", fontSize=9, fontName="Helvetica-Bold",
                                   textColor=TEXT_DARK, alignment=TA_CENTER, leading=12)
                ),
                Paragraph(
                    _grade_label(score),
                    ParagraphStyle("sg", fontSize=8, fontName="Helvetica",
                                   textColor=col, alignment=TA_CENTER, leading=10)
                ),
            ]

        inner = Table(
            [[_cell("Safety Score", safety, sc_col),
              _cell("Attention Score", attention, at_col)]],
            colWidths=[8.5 * cm, 8.5 * cm],
        )
        inner.setStyle(TableStyle([
            ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING",    (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ("LINEAFTER",     (0, 0), (0, 0), 0.5, LIGHT_LINE),
        ]))
        return inner

    # --- Cover Page ---

    def _build_cover(self, session, user):
        elements = []
        elements.append(Spacer(1, 0.4 * cm))

        safety    = session.get("safety_score",    0.0)
        attention = session.get("attention_score", 0.0)
        name      = user.get("full_name") or user.get("username", "Driver")
        start     = session.get("start_time", "")
        end       = session.get("end_time",   "")
        dur       = session.get("duration_formatted", "\u2014")
        date_str  = start[:10]   if len(start) >= 10 else "\u2014"
        t_start   = start[11:19] if len(start) >= 19 else "\u2014"
        t_end     = end[11:19]   if len(end)   >= 19 else "\u2014"
        sid       = session.get("id", "\u2014")

        # Performance score card
        score_inner = self._score_card_table(safety, attention)
        card = Table([
            [Paragraph("Session Performance",
                        ParagraphStyle("ch", fontSize=11, fontName="Helvetica-Bold",
                                       textColor=TEXT_DARK, leading=14))],
            [score_inner],
        ], colWidths=[17 * cm])
        card.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), CARD_BG),
            ("BACKGROUND",    (0, 1), (-1, 1), WHITE),
            ("TOPPADDING",    (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ("LEFTPADDING",   (0, 0), (-1, -1), 12),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 12),
            ("LINEBELOW",     (0, 0), (-1, 0), 0.5, LIGHT_LINE),
            ("BOX",           (0, 0), (-1, -1), 0.5, LIGHT_LINE),
        ]))
        elements.append(card)
        elements.append(Spacer(1, 0.4 * cm))

        # Session meta grid
        meta = [
            [Paragraph("DRIVER",       self._styles["CardLabel"]),
             Paragraph("SESSION DATE", self._styles["CardLabel"]),
             Paragraph("DURATION",     self._styles["CardLabel"]),
             Paragraph("SESSION ID",   self._styles["CardLabel"])],
            [Paragraph(name,     self._styles["CardValue"]),
             Paragraph(date_str, self._styles["CardValue"]),
             Paragraph(dur,      self._styles["CardValue"]),
             Paragraph("#%s" % sid, self._styles["CardValue"])],
            [Paragraph("",           self._styles["CardLabel"]),
             Paragraph("START TIME", self._styles["CardLabel"]),
             Paragraph("END TIME",   self._styles["CardLabel"]),
             Paragraph("",           self._styles["CardLabel"])],
            [Paragraph("",      self._styles["CardValue"]),
             Paragraph(t_start, self._styles["CardValue"]),
             Paragraph(t_end,   self._styles["CardValue"]),
             Paragraph("",      self._styles["CardValue"])],
        ]
        meta_t = Table(meta, colWidths=[4.25 * cm] * 4)
        meta_t.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), WHITE),
            ("BOX",           (0, 0), (-1, -1), 0.5, LIGHT_LINE),
            ("LINEBELOW",     (0, 1), (-1, 1), 0.5, LIGHT_LINE),
            ("LINEAFTER",     (0, 0), (2, -1), 0.5, LIGHT_LINE),
            ("TOPPADDING",    (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING",   (0, 0), (-1, -1), 10),
        ]))
        elements.append(meta_t)
        elements.append(Spacer(1, 0.4 * cm))
        return elements

    # --- Event Summary Stats ---

    def _build_event_summary(self, session):
        elements = []
        elements.append(Paragraph("Event Summary", self._styles["SectionHdr"]))
        elements.append(HRFlowable(width="100%", thickness=1,
                                   color=LIGHT_LINE, spaceAfter=8))

        eye_c   = session.get("eye_closure_count",  0)
        yawn_c  = session.get("yawn_count",          0)
        phone_c = session.get("phone_usage_count",   0)
        total_c = session.get("total_alerts",         0)

        def _cell(label, count, col):
            return [
                Paragraph(
                    "<b>%s</b>" % str(count),
                    ParagraphStyle("ec", fontSize=22, textColor=col,
                                   fontName="Helvetica-Bold",
                                   alignment=TA_CENTER, leading=26)
                ),
                Paragraph(
                    label,
                    ParagraphStyle("el", fontSize=8, textColor=TEXT_LIGHT,
                                   fontName="Helvetica",
                                   alignment=TA_CENTER, leading=10)
                ),
            ]

        stat_t = Table(
            [[_cell("Eye Closures",  eye_c,   WARNING),
              _cell("Phone Events",  phone_c, DANGER),
              _cell("Yawn Events",   yawn_c,  SUCCESS),
              _cell("Total Alerts",  total_c, PRIMARY)]],
            colWidths=[4.25 * cm] * 4,
        )
        stat_t.setStyle(TableStyle([
            ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING",    (0, 0), (-1, -1), 14),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
            ("BOX",           (0, 0), (-1, -1), 0.5, LIGHT_LINE),
            ("LINEAFTER",     (0, 0), (2, 0), 0.5, LIGHT_LINE),
            ("BACKGROUND",    (0, 0), (-1, -1), WHITE),
        ]))
        elements.append(stat_t)
        elements.append(Spacer(1, 0.4 * cm))
        return elements

    # --- Score Breakdown Progress Bars ---

    def _build_score_breakdown(self, session):
        elements = []
        elements.append(Paragraph("Score Breakdown", self._styles["SectionHdr"]))
        elements.append(HRFlowable(width="100%", thickness=1,
                                   color=LIGHT_LINE, spaceAfter=8))

        safety    = session.get("safety_score",    0.0)
        attention = session.get("attention_score", 0.0)

        rows = [
            ("Safety Score",    safety,    _score_color(safety)),
            ("Attention Score", attention, PRIMARY),
        ]
        data = []
        for label, score, col in rows:
            bar = _pct_bar(score, col, width=140, height=9)
            data.append([
                Paragraph(
                    "<b>%s</b>" % label,
                    ParagraphStyle("bl", fontSize=9, fontName="Helvetica-Bold",
                                   textColor=TEXT_DARK, leading=12)
                ),
                bar,
                Paragraph(
                    "<b>%.1f</b>" % score,
                    ParagraphStyle("sv", fontSize=9, fontName="Helvetica-Bold",
                                   textColor=col, leading=12, alignment=TA_RIGHT)
                ),
                Paragraph(
                    _grade_label(score),
                    ParagraphStyle("gr", fontSize=8, fontName="Helvetica",
                                   textColor=TEXT_LIGHT, leading=12)
                ),
            ])

        t = Table(data, colWidths=[5 * cm, 6 * cm, 2 * cm, 4 * cm])
        t.setStyle(TableStyle([
            ("VALIGN",         (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN",          (2, 0), (2, -1), "RIGHT"),
            ("TOPPADDING",     (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING",  (0, 0), (-1, -1), 10),
            ("LEFTPADDING",    (0, 0), (-1, -1), 10),
            ("RIGHTPADDING",   (0, 0), (-1, -1), 10),
            ("LINEBELOW",      (0, 0), (-1, -2), 0.5, LIGHT_LINE),
            ("BOX",            (0, 0), (-1, -1), 0.5, LIGHT_LINE),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [WHITE, CARD_BG]),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 0.4 * cm))
        return elements

    # --- Safety Recommendations ---

    def _build_recommendations(self, session, alerts):
        elements = []
        elements.append(Paragraph("Safety Recommendations", self._styles["SectionHdr"]))
        elements.append(HRFlowable(width="100%", thickness=1,
                                   color=LIGHT_LINE, spaceAfter=8))

        safety  = session.get("safety_score",    100.0)
        eye_c   = session.get("eye_closure_count",  0)
        phone_c = session.get("phone_usage_count",  0)
        yawn_c  = session.get("yawn_count",          0)

        recs = []
        if eye_c > 0 or safety < 70:
            recs.append((
                "Drowsiness and Eye Closure",
                "Multiple eye-closure events were detected. Take a break every 2 hours, "
                "consider caffeine or a short nap if feeling drowsy. Never drive when fatigued."
            ))
        if phone_c > 0:
            recs.append((
                "Mobile Phone Usage",
                "Phone use while driving is dangerous. Enable Do Not Disturb mode, "
                "use hands-free calling, or place the phone out of reach before driving."
            ))
        if yawn_c >= 3:
            recs.append((
                "Fatigue and Yawning",
                "Frequent yawning indicates fatigue. Ensure 7-8 hours of sleep before "
                "long drives. Avoid driving between midnight and 6 AM."
            ))
        if safety >= 80:
            recs.append((
                "Keep Up the Good Work!",
                "Your safety score is above 80. Stay hydrated, keep your eyes on the "
                "road, and continue your excellent driving habits."
            ))
        if not recs:
            recs.append((
                "No Major Issues Detected",
                "This session was clean. Continue practising safe driving habits and "
                "always stay alert when behind the wheel."
            ))

        rec_rows = []
        line_styles = []
        for idx, (title, body) in enumerate(recs):
            r = len(rec_rows)
            if r > 0:
                line_styles.append(("LINEABOVE", (0, r), (-1, r), 0.5, LIGHT_LINE))
            rec_rows.append([
                Paragraph(
                    "<b>%s</b>" % title,
                    ParagraphStyle("rt", fontSize=9, fontName="Helvetica-Bold",
                                   textColor=TEXT_DARK, leading=13)
                )
            ])
            rec_rows.append([
                Paragraph(
                    body,
                    ParagraphStyle("rb", fontSize=8.5, fontName="Helvetica",
                                   textColor=TEXT_MED, leading=12)
                )
            ])

        if rec_rows:
            t = Table(rec_rows, colWidths=[17 * cm])
            t.setStyle(TableStyle([
                ("BACKGROUND",    (0, 0), (-1, -1), WHITE),
                ("BOX",           (0, 0), (-1, -1), 0.5, LIGHT_LINE),
                ("TOPPADDING",    (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING",   (0, 0), (-1, -1), 14),
                ("RIGHTPADDING",  (0, 0), (-1, -1), 14),
            ] + line_styles))
            elements.append(t)

        elements.append(Spacer(1, 0.4 * cm))
        return elements

    # --- Alert Timeline Table ---

    def _build_alert_timeline(self, alerts):
        elements = []
        elements.append(Paragraph("Alert Timeline", self._styles["SectionHdr"]))
        elements.append(HRFlowable(width="100%", thickness=1,
                                   color=LIGHT_LINE, spaceAfter=8))

        if not alerts:
            ok_t = Table(
                [[Paragraph(
                    "No alerts were triggered during this session - excellent drive!",
                    ParagraphStyle("ok", fontSize=9, textColor=SUCCESS,
                                   fontName="Helvetica-Bold", leading=12)
                )]],
                colWidths=[17 * cm],
            )
            ok_t.setStyle(TableStyle([
                ("BACKGROUND",    (0, 0), (-1, -1), colors.HexColor("#F0FDF4")),
                ("BOX",           (0, 0), (-1, -1), 0.5, SUCCESS),
                ("TOPPADDING",    (0, 0), (-1, -1), 12),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
                ("LEFTPADDING",   (0, 0), (-1, -1), 14),
            ]))
            elements.append(ok_t)
            elements.append(Spacer(1, 0.4 * cm))
            return elements

        hdr_s = ParagraphStyle("th", fontSize=8.5, fontName="Helvetica-Bold",
                               textColor=WHITE, leading=11)
        row_s = ParagraphStyle("tr", fontSize=8,   fontName="Helvetica",
                               textColor=TEXT_MED, leading=10)

        rows = [[
            Paragraph("#",          hdr_s),
            Paragraph("Time",       hdr_s),
            Paragraph("Alert Type", hdr_s),
            Paragraph("Severity",   hdr_s),
            Paragraph("Message",    hdr_s),
        ]]

        for i, alert in enumerate(alerts, 1):
            ts  = alert.get("timestamp", "")
            ts  = ts[11:19] if len(ts) >= 19 else ts
            sev = alert.get("severity", "warning").upper()
            col = _severity_color(sev)
            rows.append([
                Paragraph(str(i), row_s),
                Paragraph(ts,     row_s),
                Paragraph(
                    alert.get("alert_type", "").replace("_", " ").title(),
                    row_s
                ),
                Paragraph(
                    "<b>%s</b>" % sev,
                    ParagraphStyle("sv", fontSize=8, fontName="Helvetica-Bold",
                                   textColor=col, leading=10)
                ),
                Paragraph(
                    alert.get("message", "")[:80],
                    ParagraphStyle("mg", fontSize=7.5, fontName="Helvetica",
                                   textColor=TEXT_LIGHT, leading=10)
                ),
            ])

        t = Table(rows,
                  colWidths=[1.0 * cm, 2.0 * cm, 3.5 * cm, 2.3 * cm, 8.2 * cm],
                  repeatRows=1)
        t.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), NAVY),
            ("FONTSIZE",      (0, 0), (-1, -1), 8),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, CARD_BG]),
            ("GRID",          (0, 0), (-1, -1), 0.3, LIGHT_LINE),
            ("TOPPADDING",    (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ("LEFTPADDING",   (0, 0), (-1, -1), 8),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 0.4 * cm))
        return elements

    # --- Screenshots Gallery ---

    def _build_screenshots(self, alerts):
        elements = []
        shots = [a for a in alerts
                 if a.get("screenshot_path") and os.path.exists(a["screenshot_path"])]

        if not shots:
            return elements

        elements.append(Paragraph("Alert Screenshots", self._styles["SectionHdr"]))
        elements.append(HRFlowable(width="100%", thickness=1,
                                   color=LIGHT_LINE, spaceAfter=8))
        elements.append(Paragraph(
            "%d screenshot(s) captured automatically at alert moments." % len(shots),
            ParagraphStyle("sc", fontSize=8, fontName="Helvetica",
                           textColor=TEXT_LIGHT, leading=12, spaceAfter=6)
        ))

        row = []
        for alert in shots[:12]:
            try:
                img = Image(alert["screenshot_path"], width=7.5 * cm, height=5 * cm)
                ts  = alert.get("timestamp", "")[:19].replace("T", "  ")
                sev = alert.get("severity", "warning").upper()
                cap = Paragraph(
                    "%s  |  %s  |  %s" % (
                        alert["alert_type"].replace("_", " ").title(),
                        sev, ts
                    ),
                    ParagraphStyle("ic", fontSize=7, textColor=TEXT_LIGHT,
                                   fontName="Helvetica", alignment=TA_CENTER, leading=10)
                )
                cell = Table([[img], [cap]], colWidths=[8 * cm])
                cell.setStyle(TableStyle([
                    ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
                    ("TOPPADDING",    (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ("LEFTPADDING",   (0, 0), (-1, -1), 4),
                    ("RIGHTPADDING",  (0, 0), (-1, -1), 4),
                    ("BOX",           (0, 0), (-1, -1), 0.5, LIGHT_LINE),
                    ("BACKGROUND",    (0, 1), (-1, 1), CARD_BG),
                ]))
                row.append(cell)
                if len(row) == 2:
                    grid = Table([row], colWidths=[8.5 * cm, 8.5 * cm])
                    grid.setStyle(TableStyle([
                        ("LEFTPADDING",  (0, 0), (-1, -1), 0),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                    ]))
                    elements.append(grid)
                    elements.append(Spacer(1, 0.25 * cm))
                    row = []
            except Exception as exc:
                logger.warning("Screenshot embed error: %s" % exc)

        if row:
            pad = [""] if len(row) == 1 else []
            grid = Table([row + pad], colWidths=[8.5 * cm, 8.5 * cm])
            grid.setStyle(TableStyle([
                ("LEFTPADDING",  (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ]))
            elements.append(grid)

        elements.append(Spacer(1, 0.4 * cm))
        return elements

    # --- Public: generate() ---

    def generate(self, session, user, alerts):
        """
        Generate a PDF report for the session.

        Args:
            session : DrivingSession.to_dict()
            user    : User.to_dict()
            alerts  : list of Alert.to_dict()

        Returns:
            Absolute path to the generated PDF file.
        """
        ts       = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = "report_session_%s_%s.pdf" % (session["id"], ts)
        filepath = os.path.join(REPORTS_DIR, filename)

        doc = SimpleDocTemplate(
            filepath,
            pagesize=A4,
            leftMargin=1.5 * cm, rightMargin=1.5 * cm,
            topMargin=2.2 * cm,  bottomMargin=1.8 * cm,
            title="DriveSafe AI - Safety Report",
            author="DriveSafe AI",
        )

        # Exclude session-start baseline screenshots — only real alert shots
        alert_shots = [a for a in alerts if a.get("alert_type") != "session_start"]

        elements = []
        elements += self._build_cover(session, user)
        elements += self._build_event_summary(session)
        elements += self._build_score_breakdown(session)
        elements += self._build_recommendations(session, alert_shots)
        elements += self._build_alert_timeline(alert_shots)
        elements += self._build_screenshots(alert_shots)

        doc.build(elements, onFirstPage=self._on_page, onLaterPages=self._on_page)
        logger.info("PDF report generated: %s" % filepath)
        return filepath
